<!DOCTYPE html>
<html>

<head>
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
        }

        .title {
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #007bff;
        }

        .subtitle {
            font-size: 16px;
            color: #666;
            margin-bottom: 5px;
        }

        .date {
            font-size: 14px;
            color: #888;
        }

        .program-info {
            margin-top: 30px;
        }

        .section-title {
            font-size: 20px;
            font-weight: bold;
            color: #007bff;
            margin-bottom: 15px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }

        .info-grid {
            display: table;
            width: 100%;
            margin-bottom: 25px;
        }

        .info-row {
            display: table-row;
        }

        .info-label {
            display: table-cell;
            font-weight: bold;
            padding: 8px 15px 8px 0;
            width: 150px;
            color: #555;
        }

        .info-value {
            display: table-cell;
            padding: 8px 0;
            border-bottom: 1px dotted #ddd;
        }

        .program-id {
            background-color: #f8f9fa;
            border: 2px solid #007bff;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
            margin-bottom: 25px;
        }

        .program-id .id-label {
            font-size: 14px;
            color: #666;
            margin-bottom: 5px;
        }

        .program-id .id-value {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">Program Record</div>
        <div class="subtitle">{{ $program->program_name }}</div>
        <div class="date">Generated on: {{ now()->format('F j, Y \a\t g:i A') }}</div>
    </div>

    <div class="program-id">
        <div class="id-label">Program ID</div>
        <div class="id-value">#{{ $program->id }}</div>
    </div>

    <div class="program-info">
        <div class="section-title">Basic Information</div>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Program Name:</div>
                <div class="info-value">{{ $program->program_name }}</div>
            </div>
            @if($program->department)
            <div class="info-row">
                <div class="info-label">Department:</div>
                <div class="info-value">{{ $program->department->department_name }}</div>
            </div>
            @endif
            <div class="info-row">
                <div class="info-label">Description:</div>
                <div class="info-value">{{ $program->program_description }}</div>
            </div>
        </div>

        <div class="section-title">System Information</div>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Created At:</div>
                <div class="info-value">{{ $program->created_at->format('F j, Y \a\t g:i A') }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Last Updated:</div>
                <div class="info-value">{{ $program->updated_at->format('F j, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This document was automatically generated by the Program Management System.</p>
        <p>Document ID: PROG-{{ $program->id }}-{{ now()->format('YmdHis') }}</p>
    </div>
</body>

</html>