<!DOCTYPE html>
<html>

<head>
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
        }

        .title {
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #007bff;
        }

        .subtitle {
            font-size: 16px;
            color: #666;
            margin-bottom: 5px;
        }

        .date {
            font-size: 14px;
            color: #888;
        }

        .schedule-info {
            margin-top: 30px;
        }

        .section-title {
            font-size: 20px;
            font-weight: bold;
            color: #007bff;
            margin-bottom: 15px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }

        .info-grid {
            display: table;
            width: 100%;
            margin-bottom: 25px;
        }

        .info-row {
            display: table-row;
        }

        .info-label {
            display: table-cell;
            font-weight: bold;
            padding: 8px 15px 8px 0;
            width: 150px;
            color: #555;
        }

        .info-value {
            display: table-cell;
            padding: 8px 0;
            border-bottom: 1px dotted #ddd;
        }

        .schedule-id {
            background-color: #f8f9fa;
            border: 2px solid #007bff;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
            margin-bottom: 25px;
        }

        .schedule-id .id-label {
            font-size: 14px;
            color: #666;
            margin-bottom: 5px;
        }

        .schedule-id .id-value {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">Schedule Record</div>
        <div class="subtitle">{{ $schedule->course->course_name ?? 'N/A' }}</div>
        <div class="date">Generated on: {{ now()->format('F j, Y \a\t g:i A') }}</div>
    </div>

    <div class="schedule-id">
        <div class="id-label">Schedule ID</div>
        <div class="id-value">#{{ $schedule->id }}</div>
    </div>

    <div class="schedule-info">
        <div class="section-title">Course Information</div>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Course:</div>
                <div class="info-value">
                    {{ $schedule->course->course_name ?? 'N/A' }} 
                    ({{ $schedule->course_code }})
                </div>
            </div>
            <div class="info-row">
                <div class="info-label">Section:</div>
                <div class="info-value">{{ $schedule->section->section_name ?? 'N/A' }}</div>
            </div>
        </div>

        <div class="section-title">Schedule Details</div>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Day:</div>
                <div class="info-value">{{ $schedule->day }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Time:</div>
                <div class="info-value">
                    {{ $schedule->starting_time }} - {{ $schedule->ending_time }}
                </div>
            </div>
            <div class="info-row">
                <div class="info-label">Room:</div>
                <div class="info-value">{{ $schedule->room->roomname ?? 'N/A' }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Instructor:</div>
                <div class="info-value">
                    {{ $schedule->instructor->first_name ?? 'N/A' }} 
                    {{ $schedule->instructor->last_name ?? '' }}
                </div>
            </div>
        </div>

        <div class="section-title">System Information</div>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Created At:</div>
                <div class="info-value">{{ $schedule->created_at->format('F j, Y \a\t g:i A') }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Last Updated:</div>
                <div class="info-value">{{ $schedule->updated_at->format('F j, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This document was automatically generated by the Schedule Management System.</p>
        <p>Document ID: SCH-{{ $schedule->id }}-{{ now()->format('YmdHis') }}</p>
    </div>
</body>

</html>